// Write-side of `nix-rice add`. Materializes files from the resolved closure
// to disk, regenerates the managed home-manager module, and appends to
// installed.json. Does NOT run `nh home switch` — that's the user's call.

import { mkdir, writeFile } from "node:fs/promises";
import { resolve, dirname, basename } from "node:path";
import type { RegistryItem } from "./schema.ts";
import {
  ITEMS_DIR,
  MANAGED_MODULE_PATH,
  STATE_DIR,
  readInstalled,
  writeInstalled,
  type InstalledEntry,
  type InstalledState,
} from "./state.ts";

// All files materialize as siblings of module.nix under
// `~/.config/rice-registry/items/<name>/`. The `target` field on a file
// is informational — it tells consumers "this ultimately lands at
// ~/.config/quickshell/foo/Bar.qml" — but home-manager (via
// `xdg.configFile."path".source = ./Bar.qml`) handles the actual
// deployment at activation. We don't write to absolute paths ourselves.
function siblingDest(filePath: string, itemDir: string): string {
  return resolve(itemDir, basename(filePath));
}

/** Returns the relative module.nix path under STATE_DIR if the item shipped
 * one, or null if it has no module:home file (e.g. a registry:theme that's
 * just cssVars). */
async function writeItemFiles(item: RegistryItem): Promise<string | null> {
  const itemDir = resolve(ITEMS_DIR, item.name);
  let homeModuleRelative: string | null = null;

  for (const f of item.files ?? []) {
    if (f.content === undefined) continue;
    const dest = siblingDest(f.path, itemDir);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, f.content, "utf-8");

    if (f.type === "module:home") {
      homeModuleRelative = `./items/${item.name}/${basename(f.path)}`;
    }
  }

  // For items with cssVars but no module:home (registry:theme), generate a
  // thin module that exposes the palette under `rice.theme.<name>.cssVars`.
  if (!homeModuleRelative && item.cssVars) {
    await mkdir(itemDir, { recursive: true });
    const themeNix = generateThemeModule(item);
    const themePath = resolve(itemDir, "theme.nix");
    await writeFile(themePath, themeNix, "utf-8");
    homeModuleRelative = `./items/${item.name}/theme.nix`;
  }

  return homeModuleRelative;
}

function nixString(s: string): string {
  // Quick-and-dirty Nix string literal escape. Good enough for hex colors,
  // font names, and similar palette values; revisit if values get exotic.
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\$/g, "\\$")}"`;
}

function nixAttrs(obj: Record<string, string>, indent: string): string {
  const entries = Object.entries(obj);
  if (entries.length === 0) return "{ }";
  const lines = entries.map(([k, v]) => `${indent}  ${nixString(k)} = ${nixString(v)};`);
  return `{\n${lines.join("\n")}\n${indent}}`;
}

function generateThemeModule(item: RegistryItem): string {
  const cssVars = item.cssVars ?? {};
  const lines: string[] = [];
  lines.push("# GENERATED by nix-rice from registry-item cssVars.");
  lines.push("# Re-emitted on every `nix-rice add`; do not edit.");
  lines.push("");
  lines.push("{ lib, ... }: {");
  lines.push(`  rice.themes.${item.name} = {`);
  if (cssVars.theme) lines.push(`    theme = ${nixAttrs(cssVars.theme, "    ")};`);
  if (cssVars.light) lines.push(`    light = ${nixAttrs(cssVars.light, "    ")};`);
  if (cssVars.dark) lines.push(`    dark = ${nixAttrs(cssVars.dark, "    ")};`);
  lines.push("  };");
  lines.push("}");
  return lines.join("\n") + "\n";
}

function generateManagedModule(
  installed: InstalledEntry[],
  perItem: Map<string, string | null>
): string {
  const imports: string[] = [];
  const componentEnables: string[] = [];

  for (const it of installed) {
    const rel = perItem.get(it.name);
    if (rel) imports.push(`    ${rel}`);

    if (it.type === "registry:component") {
      componentEnables.push(`  rice.components.${quoteAttr(it.name)}.enable = true;`);
    }
  }

  const importsBlock =
    imports.length === 0 ? "  imports = [ ];" : `  imports = [\n${imports.join("\n")}\n  ];`;

  return [
    "# GENERATED by nix-rice — DO NOT EDIT.",
    "# Rewritten on every `nix-rice add` / `nix-rice remove`.",
    "# Import this from your home-manager config.",
    "",
    "{ ... }: {",
    importsBlock,
    "",
    ...componentEnables,
    "}",
    "",
  ].join("\n");
}

function quoteAttr(name: string): string {
  // Nix attribute names with `-` need quoting.
  return /^[a-zA-Z_][a-zA-Z0-9_'-]*$/.test(name) && !name.includes("-") ? name : `"${name}"`;
}

export type ApplyResult = {
  newItems: string[];
  alreadyInstalled: string[];
  filesWritten: number;
};

/** Materialize every item in the resolved closure that isn't already
 * installed; refresh the managed module; persist installed.json. */
export async function applyResolved(resolved: RegistryItem[]): Promise<ApplyResult> {
  await mkdir(STATE_DIR, { recursive: true });
  await mkdir(ITEMS_DIR, { recursive: true });

  const state: InstalledState = await readInstalled();
  const installedNames = new Set(state.installed.map((e) => e.name));

  const newItems: string[] = [];
  const alreadyInstalled: string[] = [];
  const perItem = new Map<string, string | null>();

  // Pre-fill perItem from existing state — we still need to import them
  // when regenerating the managed module. Trust the names; the actual
  // module.nix file is on disk from a prior install.
  for (const e of state.installed) {
    perItem.set(e.name, await guessExistingModuleRel(e));
  }

  let filesWritten = 0;
  for (const it of resolved) {
    if (installedNames.has(it.name)) {
      alreadyInstalled.push(it.name);
      continue;
    }
    const rel = await writeItemFiles(it);
    perItem.set(it.name, rel);
    if (it.files) filesWritten += it.files.length;
    if (rel?.endsWith("theme.nix")) filesWritten += 1; // synthesized

    state.installed.push({
      name: it.name,
      type: it.type,
      addedAt: new Date().toISOString(),
    });
    newItems.push(it.name);
  }

  await writeInstalled(state);

  const moduleSource = generateManagedModule(state.installed, perItem);
  await writeFile(MANAGED_MODULE_PATH, moduleSource, "utf-8");

  return { newItems, alreadyInstalled, filesWritten };
}

/** When regenerating the managed module after install/remove, we need to
 * know each item's module path. For items installed in the past, we don't
 * have the original RegistryItem in hand — guess from convention. */
async function guessExistingModuleRel(entry: InstalledEntry): Promise<string | null> {
  // Heuristic: components have module.nix; themes have theme.nix; bases
  // typically have neither. The `state.ts` export ITEMS_DIR is the parent.
  if (entry.type === "registry:component" || entry.type === "registry:layout") {
    return `./items/${entry.name}/module.nix`;
  }
  if (entry.type === "registry:theme") {
    return `./items/${entry.name}/theme.nix`;
  }
  return null;
}
