// Write-side of `nix-rice add`. Materializes files from the resolved closure
// to disk, regenerates the managed home-manager module, and appends to
// installed.json. Does NOT run `nh home switch` — that's the user's call.

import { mkdir, writeFile } from "node:fs/promises";
import { resolve, dirname, basename } from "node:path";
import type { RegistryItem } from "./schema.ts";
import {
  ITEMS_DIR,
  MANAGED_MODULE_PATH,
  STATE_DIR,
  readInstalled,
  writeInstalled,
  type InstalledEntry,
} from "./state.ts";

// All files materialize as siblings of module.nix under
// `~/.config/rice-registry/items/<name>/`. The `target` field on a file
// is informational — it tells consumers "this ultimately lands at
// ~/.config/quickshell/foo/Bar.qml" — but home-manager (via
// `xdg.configFile."path".source = ./Bar.qml`) handles the actual
// deployment at activation. We don't write to absolute paths ourselves.
function siblingDest(filePath: string, itemDir: string): string {
  return resolve(itemDir, basename(filePath));
}

/** Returns the relative module-path under STATE_DIR if the item shipped
 * a home-manager module (or we synthesized one for a theme), or null. */
async function writeItemFiles(item: RegistryItem): Promise<string | null> {
  const itemDir = resolve(ITEMS_DIR, item.name);
  let homeModuleRelative: string | null = null;

  for (const f of item.files ?? []) {
    if (f.content === undefined) continue;
    const dest = siblingDest(f.path, itemDir);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, f.content, "utf-8");

    if (f.type === "module:home") {
      homeModuleRelative = `./items/${item.name}/${basename(f.path)}`;
    }
  }

  // For items with cssVars but no module:home (registry:theme), generate a
  // thin module that exposes the palette under `rice.themes.<name>.cssVars`.
  if (!homeModuleRelative && item.cssVars) {
    await mkdir(itemDir, { recursive: true });
    const themeNix = generateThemeModule(item);
    const themePath = resolve(itemDir, "theme.nix");
    await writeFile(themePath, themeNix, "utf-8");
    homeModuleRelative = `./items/${item.name}/theme.nix`;
  }

  return homeModuleRelative;
}

function nixString(s: string): string {
  return `"${s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\$/g, "\\$")}"`;
}

function nixAttrs(obj: Record<string, string>, indent: string): string {
  const entries = Object.entries(obj);
  if (entries.length === 0) return "{ }";
  const lines = entries.map(([k, v]) => `${indent}  ${nixString(k)} = ${nixString(v)};`);
  return `{\n${lines.join("\n")}\n${indent}}`;
}

function generateThemeModule(item: RegistryItem): string {
  const cssVars = item.cssVars ?? {};
  const lines: string[] = [];
  lines.push("# GENERATED by nix-rice from registry-item cssVars.");
  lines.push("# Re-emitted on every `nix-rice add`; do not edit.");
  lines.push("");
  lines.push("{ lib, ... }: {");
  lines.push(`  rice.themes.${item.name} = {`);
  if (cssVars.theme) lines.push(`    theme = ${nixAttrs(cssVars.theme, "    ")};`);
  if (cssVars.light) lines.push(`    light = ${nixAttrs(cssVars.light, "    ")};`);
  if (cssVars.dark) lines.push(`    dark = ${nixAttrs(cssVars.dark, "    ")};`);
  lines.push("  };");
  lines.push("}");
  return lines.join("\n") + "\n";
}

function quoteAttr(name: string): string {
  return /^[a-zA-Z_][a-zA-Z0-9_']*$/.test(name) ? name : `"${name}"`;
}

function generateManagedModule(installed: InstalledEntry[]): string {
  const imports: string[] = [];
  const componentEnables: string[] = [];

  for (const it of installed) {
    if (it.homeModule) imports.push(`    ${it.homeModule}`);
    if (it.type === "registry:component") {
      componentEnables.push(`  rice.components.${quoteAttr(it.name)}.enable = true;`);
    }
  }

  const importsBlock =
    imports.length === 0 ? "  imports = [ ];" : `  imports = [\n${imports.join("\n")}\n  ];`;

  return [
    "# GENERATED by nix-rice — DO NOT EDIT.",
    "# Rewritten on every `nix-rice add` / `nix-rice remove`.",
    "# Import this from your home-manager config.",
    "",
    "{ ... }: {",
    importsBlock,
    "",
    ...componentEnables,
    "}",
    "",
  ].join("\n");
}

/** Read the current installed state and rewrite the managed module from it.
 * Used by both `add` (after appending new items) and `remove` (after popping). */
export async function regenerateManagedModule(): Promise<void> {
  const state = await readInstalled();
  await writeFile(MANAGED_MODULE_PATH, generateManagedModule(state.installed), "utf-8");
}

export type ApplyResult = {
  newItems: string[];
  alreadyInstalled: string[];
  filesWritten: number;
};

/** Materialize every item in the resolved closure that isn't already
 * installed; refresh the managed module; persist installed.json. */
export async function applyResolved(resolved: RegistryItem[]): Promise<ApplyResult> {
  await mkdir(STATE_DIR, { recursive: true });
  await mkdir(ITEMS_DIR, { recursive: true });

  const state = await readInstalled();
  const installedNames = new Set(state.installed.map((e) => e.name));

  const newItems: string[] = [];
  const alreadyInstalled: string[] = [];
  let filesWritten = 0;

  for (const it of resolved) {
    if (installedNames.has(it.name)) {
      alreadyInstalled.push(it.name);
      continue;
    }
    const homeModule = await writeItemFiles(it);
    if (it.files) filesWritten += it.files.length;
    if (homeModule?.endsWith("theme.nix")) filesWritten += 1; // synthesized

    state.installed.push({
      name: it.name,
      type: it.type,
      addedAt: new Date().toISOString(),
      ...(homeModule ? { homeModule } : {}),
    });
    newItems.push(it.name);
  }

  await writeInstalled(state);
  await writeFile(MANAGED_MODULE_PATH, generateManagedModule(state.installed), "utf-8");

  return { newItems, alreadyInstalled, filesWritten };
}
