// State file at ~/.config/rice-registry/installed.json — tracks what
// rices/components/themes the user has installed. Drives conflict
// detection on subsequent installs.
//
// Schema:
//   {
//     "version": 1,
//     "installed": [
//       { "name": "mountain-mist", "type": "registry:theme", "addedAt": "..." },
//       ...
//     ]
//   }

import { readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { resolve } from "node:path";
import { homedir } from "node:os";

export const STATE_DIR = resolve(homedir(), ".config", "rice-registry");
export const INSTALLED_PATH = resolve(STATE_DIR, "installed.json");
export const MANAGED_MODULE_PATH = resolve(STATE_DIR, "rice-registry.nix");
export const ITEMS_DIR = resolve(STATE_DIR, "items");

export type InstalledEntry = {
  name: string;
  type: string;
  addedAt: string;
  /** Relative path (from STATE_DIR) to this item's home-manager module
   * file, if any. Used by the managed-module regenerator. */
  homeModule?: string;
};

export type MachineProfile = {
  /** Versions the user has installed of substrate tools. Drives
   * compatibility checks. Optional — when absent, compat checks are
   * skipped with a note. */
  hyprland?: string;
  quickshell?: string;
  waybar?: string;
  stylix?: string;
  homeManager?: string;
  nixpkgs?: string;
};

export type InstalledState = {
  version: 1;
  installed: InstalledEntry[];
  machine?: MachineProfile;
};

export async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

export async function readInstalled(): Promise<InstalledState> {
  if (!(await exists(INSTALLED_PATH))) {
    return { version: 1, installed: [] };
  }
  const raw = await readFile(INSTALLED_PATH, "utf-8");
  const parsed = JSON.parse(raw) as InstalledState;
  if (parsed.version !== 1) {
    throw new Error(
      `installed.json has version ${parsed.version}; expected 1. ` + `delete or migrate manually.`
    );
  }
  return parsed;
}

export async function writeInstalled(state: InstalledState): Promise<void> {
  await mkdir(STATE_DIR, { recursive: true });
  await writeFile(INSTALLED_PATH, JSON.stringify(state, null, 2) + "\n", "utf-8");
}

/** Stable Nix module that imports nothing yet — overwritten by `add` later. */
export const EMPTY_MANAGED_MODULE = `# GENERATED by nix-rice — DO NOT EDIT.
# This file is rewritten on every \`nix-rice add\` / \`nix-rice remove\`.
# Import it from your home-manager config:
#
#   { ... }: {
#     imports = [ ./rice-registry.nix ];
#   }
#
# Or via the \`<rice>\` channel-style alias once that's set up.

{ ... }: {
  imports = [ ];
}
`;
